requires 'Digest::SHA';
requires 'Email::Valid';
requires 'Encode';
requires 'Getopt::Long';
requires 'HTTP::Tiny';
requires 'JSON';
requires 'Mojolicious::Plugin::Number::Commify';
requires 'Moo';
requires 'Pod::Usage';
